(CI) Added errors check for unit tests.

diff --git a/.github/workflows/LinuxTestsCI.yml b/.github/workflows/LinuxTestsCI.yml
--- a/.github/workflows/LinuxTestsCI.yml
+++ b/.github/workflows/LinuxTestsCI.yml
@@ -72,7 +72,7 @@ jobs:
 
       - name: Run Debug tests
         shell: bash
-        continue-on-error: true
+        continue-on-error: false
         run: |
           BIN="${{ steps.find_debug.outputs.debug_bin }}"
           echo "Running: $BIN"
@@ -110,10 +110,17 @@ jobs:
 
           echo "===== Test Log ====="
           cat "$log_test"
+          
+          if grep -q "Debugger has been stopped with errors!" "$log_test"; then
+            echo "❌ Found error message in log!"
+            exit 1
+          else
+            echo "✅ No error message found."
+          fi
 
       - name: Run Release tests
         shell: bash
-        continue-on-error: true
+        continue-on-error: false
         run: |
           BIN="${{ steps.find_release.outputs.release_bin }}"
           echo "Running: $BIN"
@@ -151,3 +158,10 @@ jobs:
 
           echo "===== Test Log ====="
           cat "$log_test"
+          
+          if grep -q "Debugger has been stopped with errors!" "$log_test"; then
+            echo "❌ Found error message in log!"
+            exit 1
+          else
+            echo "✅ No error message found."
+          fi
diff --git a/.github/workflows/WindowsTestsCI.yml b/.github/workflows/WindowsTestsCI.yml
--- a/.github/workflows/WindowsTestsCI.yml
+++ b/.github/workflows/WindowsTestsCI.yml
@@ -56,7 +56,7 @@ jobs:
 
       - name: Run Debug tests
         shell: powershell
-        continue-on-error: true
+        continue-on-error: false
         run: |
           $exe = "${{ steps.find_debug.outputs.debug_exe }}"
           Write-Host "Running: $exe"
@@ -106,10 +106,20 @@ jobs:
 
           Write-Host "===== Test Log ====="
           Get-Content $logFile
+          
+          $logContent = Get-Content $logFile -Raw
+  
+          if ($logContent -match "Debugger has been stopped with errors!") {
+            Write-Host "❌ Found error message in log!"
+            exit 1
+          }
+          else {
+            Write-Host "✅ No error message found."
+          }
 
       - name: Run Release tests
         shell: powershell
-        continue-on-error: true
+        continue-on-error: false
         run: |
           $exe = "${{ steps.find_release.outputs.release_exe }}"
           Write-Host "Running: $exe"
@@ -159,4 +169,15 @@ jobs:
 
           Write-Host "===== Test Log ====="
           Get-Content $logFile
+          
+          $logContent = Get-Content $logFile -Raw
+          
+          if ($logContent -match "Debugger has been stopped with errors!") {
+            Write-Host "❌ Found error message in log!"
+            exit 1
+          }
+          else {
+            Write-Host "✅ No error message found."
+          }
+
 
